version: "3"
services:
  db:
    image: "postgres"
    container_name: "LocalFix2024"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=lf2024
      - POSTGRES_DB=localfix
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: